services:
  user-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: prueba-chakray-api
    image: prueba-chakray:1.0.0
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=9001
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped
    networks:
      - user-api-network

networks:
  user-api-network:
    driver: bridge
