# Etapa 1: compilación
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests=true

# Etapa 2: ejecución
FROM openjdk:17-jdk-alpine
LABEL maintainer="Juan <juachg2108@gmail.com>" \
      version="1.0" \
      description="Aplicación Spring Boot Cine"

WORKDIR /app
COPY --from=builder /build/target/Cine-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 9005
ENTRYPOINT ["java", "-jar", "app.jar"]
