version: '3.8'

services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "${APP_PORT:-9000}:9000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on: []
